### ISSUE TITLE
Bot received message

### ISSUE THREAD

**Issue by fnrcum** [Paul-weqe/python_webex_bot#1]
Hi, I've been using this library but there's 1 thing i can't figure out for the life of me.
When the bot hears a certain message, how can i parse that message inside the bot method?

For example here:
```
@bot.on_hears("*")
def default_response(room_id=None, text=None):
    print(text)
    return bot.send_message(room_id=room_id, text="Sorry, could not understand that")
```

I tried this just to see if i can get the message to parse it but nothing and as of now the documentation is very lacking.

**Comment by Paul-weqe** [comment]
@fnrcum really sorry for the long time to respond. I have been off this project for a while and have not been constantly looking into issues but now I am dedicating a larger amount of time this and other open source projects I have been working on. 

So, if I get you correctly, you are trying to send a message inside the default_response function without placing the `bot.send_message(room_id=room_id, text="Sorry, could not understand that")` it at the return statement. 

The following should work: 

```
@bot.on_hears("*")
def default_response(room_id=None, text=None):
     bot.send_message(room_id=room_id, text="Sorry, could not understand that")
     return None
```

Note that it is not a must for the bot's actions to be at the return statement, you can keep them anywhere in the middle of the function. I am not sure if I got your issue right, please let me know. 

Again, sorry for the late response, since I have been off the project for a while. I have added some  new features from Cisco Webex API to the Library. Be sure the project will be under active development from now on. 

It is a growing project and you can try out various things and let me know the issues you have. Also feel free to contribute to the development of the actual project. The code is still simple enough to understand.

**Comment by Paul-weqe** [comment]
Hello @fnrcum I will be closing this issue, please let us know if there are any other issues that arise in the future.
